on:
  push:
    branches:
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install docker ğŸ¬
        run: sudo snap install docker

      - name: Setup SSH key ğŸ”‘
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_JONION_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Setup SSH config ğŸ“„
        run: |
          echo "Host server" >> ~/.ssh/config
          echo "  HostName jonion.duckdns.org" >> ~/.ssh/config
          echo "  User server" >> ~/.ssh/config
          echo "  IdentityFile ~/.ssh/id_rsa" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Setup docker ğŸ¬
        run: |
          export DOCKER_HOST='ssh://server@jonion.duckdns.org'

      - name: Deploy ğŸš€
        run: |
          docker-compose up -d --force-recreate
