on:
  push:
    branches:
      - production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install docker ğŸ¬
        run: sudo snap install docker

      - name: Setup SSH key ğŸ”‘
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SERVER_JONION_SSH_KEY }}

      - name: Deploy ğŸš€
        run: |
          export DOCKER_HOST='ssh://server@jonion.duckdns.org'
          docker-compose up -d --force-recreate
